const vcs = {
  totalCount: 2025,
  countExceeded: true,
  '@count': 2000,
  value: [
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2343',
      resourceName: 'Zhanjiang Mangrove Afforestation Project',
      proponent:
        'Third Institute of Oceanography, Ministry of Natural Resources',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'China',
      estAnnualEmissionReductions: 2554,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-AM0014',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-09-01'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2342',
      resourceName:
        'Installation of high efficiency wood burning cookstoves in Malawi',
      proponent: 'C-Quest Capital Stoves Asia Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'Malawi',
      estAnnualEmissionReductions: 800000,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G., VMR0006',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-08-31'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2337',
      resourceName: 'Sanya Landfill Gas Power Generation Project',
      proponent: 'Swiss carbon Value Ltd.',
      operator: null,
      designee: null,
      protocolCategories:
        'Waste handling and disposal, Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'China',
      estAnnualEmissionReductions: 89751,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'ACM0001',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-08-12'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2336',
      resourceName: 'Energy Efficient Cook Stove Implementation in India',
      proponent: 'Enen Green Services Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 35472,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-08-11'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2335',
      resourceName: 'Zhangjiakou Landfill Gas Power Generation Project',
      proponent: 'Swiss carbon Value Ltd.',
      operator: null,
      designee: null,
      protocolCategories:
        'Waste handling and disposal, Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'China',
      estAnnualEmissionReductions: 137098,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'ACM0001',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-08-10'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2334',
      resourceName: 'Oaxaca II Wind Energy Project.',
      proponent: 'Converted From a another GHG program CDM',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Credits Transferred from Approved GHG Program',
      country: 'Mexico',
      estAnnualEmissionReductions: 240159,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-08-06'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2332',
      resourceName: 'Culiacan Norther Landfill Ga Project',
      proponent: 'Converted From a another GHG program CDM',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal',
      resourceStatus: 'Credits Transferred from Approved GHG Program',
      country: 'Mexico',
      estAnnualEmissionReductions: 42746,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'ACM0001',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-08-04'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2333',
      resourceName:
        'Landfill Gas Recovery and Flaring Project in the El Verde Landfill, León',
      proponent: 'Converted From a another GHG program CDM',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal',
      resourceStatus: 'Credits Transferred from Approved GHG Program',
      country: 'Mexico',
      estAnnualEmissionReductions: 177705,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'ACM0001',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-08-04'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2330',
      resourceName:
        'Protection of mangroves and community developmental activities in the biodiversity hotspot of Colombia',
      proponent: 'WeAct Pty Ltd',
      operator: null,
      designee: null,
      protocolCategories:
        'Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'Colombia',
      estAnnualEmissionReductions: 460000,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM0015',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-07-30'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2326',
      resourceName:
        'Guangxi Jinxiu IFM (conversion  of  logged  to  protected  forest)  Project',
      proponent: 'Guangzhou Guotan Assets Management Co., Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'China',
      estAnnualEmissionReductions: 84500,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'VM0010',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-07-23'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2327',
      resourceName:
        'Guangxi Huanjiang IFM (conversion of logged to protected forest) Project',
      proponent:
        'Guangzhou Guangtan Carbon Emission Development & Investment CO.,Ltd',
      operator: null,
      designee: null,
      protocolCategories:
        'Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'China',
      estAnnualEmissionReductions: 54140,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'VM0010',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-07-23'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2324',
      resourceName:
        'COMMUNITY BASED AVOIDED DEFORESTATION PROJECT IN GUINEA-BISSAU - REDD',
      proponent: 'BioGuinea Foundation',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registration and verification approval requested',
      country: 'Guinea-Bissau',
      estAnnualEmissionReductions: 920436,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'VM0007',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-07-16'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2323',
      resourceName:
        '7 MW Bundled Hydro power project at Himachal Pradesh of Raajratna Energy Holdings Pvt. Ltd',
      proponent: 'M/s Raajratna Energy Holdings Pvt Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 19693,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-07-09'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2318',
      resourceName: 'Luviro hydro plant',
      proponent: 'AERA Group',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under validation',
      country: 'Congo, The Democratic Republic of The',
      estAnnualEmissionReductions: 26529,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AMS-I.L.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-29'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2319',
      resourceName:
        'Agroforestry plantation Bateke Plateaus, Republic of Congo',
      proponent: 'Agroforestry plantation Bateke Plateaus, Republic of Congo',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Congo',
      estAnnualEmissionReductions: 22728,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-29'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2316',
      resourceName:
        'BRASCARBON Methane Recovery Project BCA-BRA-08, Brazil CDM',
      proponent: 'Converted From a another GHG program CDM',
      operator: null,
      designee: null,
      protocolCategories:
        'Livestock, enteric fermentation, and manure management',
      resourceStatus: 'Credits Transferred from Approved GHG Program',
      country: 'Brazil',
      estAnnualEmissionReductions: 27418,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'AMS-III.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2317',
      resourceName: 'Proyecto REDD+ Magnolios',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Colombia',
      estAnnualEmissionReductions: 8202,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM00015',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2311',
      resourceName:
        'Madagascar Improved Cookstove Project by KCM-Wood#CPA-W-001',
      proponent: 'Korea Carbon Management Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Registered',
      country: 'Madagascar',
      estAnnualEmissionReductions: 37722,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-17'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2312',
      resourceName:
        'Madagascar Improved Cookstove Project by KCM-Wood#CPA-W-002',
      proponent: 'Korea Carbon Management Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Under validation',
      country: 'Madagascar',
      estAnnualEmissionReductions: 37950,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-17'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2313',
      resourceName:
        'Madagascar Improved Cookstove Project by KCM-Wood#CPA-W-003',
      proponent: 'Korea Carbon Management Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Under validation',
      country: 'Madagascar',
      estAnnualEmissionReductions: 37950,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-17'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2314',
      resourceName:
        'Madagascar Improved Cookstove Project by KCM-Wood#CPA-W-004',
      proponent: 'Korea Carbon Management Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Under validation',
      country: 'Madagascar',
      estAnnualEmissionReductions: 37950,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-17'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2315',
      resourceName:
        'Madagascar Improved Cookstove Project by KCM-Wood#CPA-W-005',
      proponent: 'Korea Carbon Management Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Under validation',
      country: 'Madagascar',
      estAnnualEmissionReductions: 37950,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-17'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2310',
      resourceName: 'Anhuang Afforestation Project',
      proponent: 'Guizhou Xinzhanxin Agricultural Technology Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'China',
      estAnnualEmissionReductions: 607596,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-12'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2309',
      resourceName: 'Henrietta solar PV project',
      proponent: 'AERA Group',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Mauritius',
      estAnnualEmissionReductions: 26254,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-08'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2307',
      resourceName: 'Ambatolampy 20 MW solar PV',
      proponent: 'AERA Group',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration and verification approval requested',
      country: 'Madagascar',
      estAnnualEmissionReductions: 23431,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-05'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2308',
      resourceName: 'Solitude 16 MW solar PV',
      proponent: 'AERA Group',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under validation',
      country: 'Mauritius',
      estAnnualEmissionReductions: 28984,
      region: 'Africa',
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-05'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2306',
      resourceName: 'São João Landfill Gas to Energy Project (SJ)',
      proponent: 'Converted from other GHG program',
      operator: null,
      designee: null,
      protocolCategories:
        'Energy industries (renewable/non-renewable sources), Waste handling and disposal',
      resourceStatus: 'Credits Transferred from Approved GHG Program',
      country: 'Brazil',
      estAnnualEmissionReductions: 76429,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'ACM0001',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-04'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2305',
      resourceName:
        'Zhangjiakou Yuxian Afforestation Project in Hebei Province',
      proponent: 'Zhangjiakou Sailin Landscaping Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'China',
      estAnnualEmissionReductions: 70374,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-03'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2303',
      resourceName:
        'Energy Efficient Cooking Solution for low emission development in Nepal - 2',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Nepal',
      estAnnualEmissionReductions: 33672,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-01'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2304',
      resourceName:
        'Energy Efficient Cooking Solution for low emission development in Nepal - 3',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under validation',
      country: 'Nepal',
      estAnnualEmissionReductions: 33715,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-06-01'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2302',
      resourceName: 'Guizhou Dongyijing CMM Power Generation Project',
      proponent: 'Liupanshui Zhongding New Energy Development Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories:
        'Fugitive emissions from fuels (solid, oil and gas), Mining/mineral production',
      resourceStatus: 'Registration and verification approval requested',
      country: 'China',
      estAnnualEmissionReductions: 174220,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'ACM0008',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-29'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2301',
      resourceName:
        'Zhangjiakou Chongli Afforestation Project in Hebei Province',
      proponent: 'Zhangjiakou Sailin Landscaping Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'China',
      estAnnualEmissionReductions: 97103,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-28'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2300',
      resourceName:
        'Energy Efficient Cooking Solution for low emission development in Nepal-1',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under validation',
      country: 'Nepal',
      estAnnualEmissionReductions: 33685,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2299',
      resourceName: 'Hunan Xiangtan Landfill Gas Power Generation Project',
      proponent: 'Swiss carbon Value Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 104582,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'ACM0001',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2298',
      resourceName:
        'CONSEJOS COMUNITARIOS DEL PACIFICO VALLE DEL CAUCA (CCPVC) PROGRAMA REDD+ VALLE DEL CAUCA, COLOMBIA',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Colombia',
      estAnnualEmissionReductions: 796394,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM0006',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-18'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2297',
      resourceName: 'REDD Project Predio Putumayo',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Colombia',
      estAnnualEmissionReductions: 2365816,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM0037',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2296',
      resourceName:
        'CYY Global Plus Wastewater Treatment and Biogas Utilization Project',
      proponent: 'Swiss carbon Value Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal',
      resourceStatus: 'Under development',
      country: 'Thailand',
      estAnnualEmissionReductions: 96094,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'ACM0014',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-14'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2293',
      resourceName: 'NIHT Topaiyo REDD +',
      proponent: 'NIHT Inc.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registered',
      country: 'Papua New Guinea',
      estAnnualEmissionReductions: 2262521,
      region: 'Oceania',
      version: 'VCS Version 3',
      protocols: 'VM0009',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-06'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2291',
      resourceName:
        'Guizhou Panjiang Low Concentration Coal Mine Methane Power Generation Project Phase 2',
      proponent: 'Guizhou Panjiang CBM Development&Utilization Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories:
        'Fugitive emissions from fuels (solid, oil and gas), Mining/mineral production',
      resourceStatus: 'Registration and verification approval requested',
      country: 'China',
      estAnnualEmissionReductions: 419925,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'ACM0008',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-02'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2292',
      resourceName:
        'Guizhou Panjiang Low Concentration Coal Mine Methane Power Generation Project Phase 3',
      proponent: 'Guizhou Panjiang CBM Development&Utilization Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories:
        'Fugitive emissions from fuels (solid, oil and gas), Mining/mineral production',
      resourceStatus: 'Registration and verification approval requested',
      country: 'China',
      estAnnualEmissionReductions: 589187,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'ACM0008',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-02'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2290',
      resourceName: 'BLUE CARBON PROJECT GULF OF MORROSQUILLO “VIDA MANGLAR”',
      proponent: 'Conservation International Foundation',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Colombia',
      estAnnualEmissionReductions: 7646,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM0007',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-05-01'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2278',
      resourceName: 'The Jaguar Amazon REDD Project',
      proponent: 'Greenoxx NGO',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'Peru',
      estAnnualEmissionReductions: 3751851,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM0006',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-04-16'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '895',
      resourceName:
        '20.8 MW Grid connected wind electricity generation project at Dhule, Maharashtra.',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 33008,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-04-01'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '733',
      resourceName:
        'Biomass based steam generation project by Gujarat Ambuja Exports Ltd.',
      proponent: 'Gujarat Ambuja Exports Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 45523,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.C.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-30'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2263',
      resourceName:
        'Renewable Energy based power generation projects in Bangladesh',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories:
        'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration and verification approval requested',
      country: 'Bangladesh',
      estAnnualEmissionReductions: 32791,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002, AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1310',
      resourceName:
        'Guohua Tongliao Kezuo Zhongqi Phase I 49.5 MW Wind Farm Project',
      proponent: 'Guohua (Tongliao) Wind Power Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 111877,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2099',
      resourceName:
        'Ningbo Yinzhou Landfill Gas Recovery and Utilization Project',
      proponent: 'Ningbo Micropowers New Energy Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories:
        'Waste handling and disposal, Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 88139,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0001',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2262',
      resourceName: 'REDD+ Yaguara Llanos del Yari',
      proponent: 'CUESTA Y ASOCIADOS SAS',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Colombia',
      estAnnualEmissionReductions: 3478764,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM0015',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-24'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '854',
      resourceName:
        'Waste Gas-based Cogeneration Project at Alexandria Carbon Black',
      proponent: 'Alexandria Carbon Black Co. S.A.E.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Egypt',
      estAnnualEmissionReductions: 26597,
      region: null,
      version: 'VCS Version 3',
      protocols: 'VCS v1 Project Specific',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-16'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2261',
      resourceName:
        'CYY Biopower Wastewater treatment plant including biogas reuse for thermal oil replacement and electricity generation Project, Thailand.',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories:
        'Waste handling and disposal, Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Thailand',
      estAnnualEmissionReductions: 84912,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0014',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-16'
    }
  ]
}

module.exports = {
  vcs
}
