const vcs = {
  "totalCount": 2026,
  "countExceeded": true,
  "@count": 2000,
  "value": [
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1167",
      "resourceName": "Shri Bajrang RE Project",
      "proponent": "Shri Bajrang Power and Ispat Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 37717,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-31"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "764",
      "resourceName": "Yunnan Maguan Laqi Hydropower Project",
      "proponent": "Maguan Laqi Power Generation Co.,",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 174517,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-29"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1767",
      "resourceName": "Bundled Solar Power Project by Mahindra Susten Private Limited",
      "proponent": "Mahindra Susten Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 329360,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1766",
      "resourceName": "Outapi Pv Plant",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Namibia",
      "estAnnualEmissionReductions": 16689,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1765",
      "resourceName": "Grouped Project for reducing emissions from deforestation and forest degradation-REDD-in the Regional Natural Park:Biological Corridor PNN Purace-PNN Cueva de los Guacharos",
      "proponent": "Corporación Autónoma Regional del Río Grande de la Magdalena (CORMAGDALENA)",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registration requested",
      "country": "Colombia",
      "estAnnualEmissionReductions": 117468,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "ACM0015",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "309",
      "resourceName": "Bundled grid-connected wind electricity generation project identified as Bundle E3 in Maharashtra and Gujarat, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 11922,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1181",
      "resourceName": "CGN Inner Mongolia Zhurihe Phase II Wind Farm Project",
      "proponent": "CGN Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 119319,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1182",
      "resourceName": "CGN Inner Mongolia Zhurihe Phase I Wind Farm Project",
      "proponent": "CGN Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 130755,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1183",
      "resourceName": "Xinjiang Jimunai CGN Phase I Wind Farm Project",
      "proponent": "Xinjiang Jimunai CGN Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 107695,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1762",
      "resourceName": "Bundled Solar Power Project by Solararise India Projects PVT. LTD.",
      "proponent": "SolarArise India Projects Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 244968,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-08"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1759",
      "resourceName": "Methane Recovery and Power Generation Project at ESIPL",
      "proponent": "Everest Starch (IND) Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 52036,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.H.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-04"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1760",
      "resourceName": "The Haidar EL ALI Mangrove Initiative (HEAMI)",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under development",
      "country": "Senegal",
      "estAnnualEmissionReductions": 30170,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-AMS0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-04"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1758",
      "resourceName": "Dereli Hydroelectric Power  Plant",
      "proponent": "Karadeniz Elektrik Uretim Sanayi A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 83983,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-04-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "766",
      "resourceName": "Teesta- V Hydro Power project in Sikkim",
      "proponent": "NHPC Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 2044442,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-04-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "730",
      "resourceName": "Electricity generation from 17.10 MW bundled wind energy project in Maharashtra aggregated by Resurge Energy Private Limited",
      "proponent": "RESURGE ENERGY PRIVATE LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 26730,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-04-23"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "368",
      "resourceName": "Sulige Natural Gas based Power Generation Project",
      "proponent": "Sulige Fuel Gas Power Generation Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 504618,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, AM0029",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-04-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1753",
      "resourceName": "Bundled Solar Photovoltaic Project by ACME",
      "proponent": "ACME Cleantech Solutions Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 2078589,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-04-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1754",
      "resourceName": "Reading Wind Energy, LLC",
      "proponent": "Southern Power Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "United States",
      "estAnnualEmissionReductions": 512840,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-04-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1752",
      "resourceName": "TW Ghana ODS Project",
      "proponent": "Tradewater, LLC",
      "operator": null,
      "designee": null,
      "protocolCategories": "Chemical industry",
      "resourceStatus": "Registered",
      "country": "Ghana",
      "estAnnualEmissionReductions": 97000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": null,
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-04-03"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1751",
      "resourceName": "Bundled Wind power project in Tamilnadu, India co-ordinated by the TamilNadu Spinning Mills Association (TASMA)",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "India",
      "estAnnualEmissionReductions": 686697,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-29"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1750",
      "resourceName": "PFC Emission Reductions at PT. Indonesia Asahan Aluminium (PT. INALUM) Kuala Tanjung",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Metal production",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "Indonesia",
      "estAnnualEmissionReductions": 78041,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0030",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "249",
      "resourceName": "Bundled Wind Power Project in Tamilnadu, India, Co-ordinated by Tamilnadu Spinning Mills Association(TASMA-II)",
      "proponent": "TAMILNADU SPINNING MILLS ASSOCIATION (TASMA)",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 758093,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1748",
      "resourceName": "Southern Cardamom REDD+ Project",
      "proponent": "Royal Government of Cambodia (RGC), Ministry of Environment",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Cambodia",
      "estAnnualEmissionReductions": 3867568,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "VM0009",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "974",
      "resourceName": "Sarbari II hydro power project by DSL Hydrowatt Limited in Kullu, Himachal Pradesh",
      "proponent": "DSL Hydrowatt Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 27626,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1002",
      "resourceName": "Natural Gas based grid connected power project at Peddapuram, A.P. by Gautami Power Limited",
      "proponent": "GVK Industries Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1293422,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0029",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "483",
      "resourceName": "Sarbari-I small hydro project of DSL Hydrowatt Limited (DSLHL), Himachal Pradesh, India",
      "proponent": "DSL Hydrowatt Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 23425,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1746",
      "resourceName": "108 MW Fatanpur Wind Power Project in Madhya Pradesh",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 212745,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-03-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "405",
      "resourceName": "Banpong Tapioca Flour Industrial Wastewater Treatment and Biogas Utilisation Project",
      "proponent": "Banpong Tapioca Flour Industrial Co.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal",
      "resourceStatus": "Registered",
      "country": "Thailand",
      "estAnnualEmissionReductions": 42708,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.H.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "725",
      "resourceName": "Shibeishan Wind Power Generation Project in Huilai County, Guangdong Province",
      "proponent": "Guangdong Yudean Shibeishan Wind Power Development",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 120288,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-23"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1743",
      "resourceName": "Beampingaratsy REDD Project",
      "proponent": "BNC REDD+",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registration requested",
      "country": "Madagascar",
      "estAnnualEmissionReductions": 19867,
      "region": "Africa",
      "version": "VCS Version 3",
      "protocols": "VM0007",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1744",
      "resourceName": "4 MW Biomass based cogeneration plant by Godrej Agrovet Ltd.",
      "proponent": "Godrej Agrovet Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 97671,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1745",
      "resourceName": "Bundled Solar Power Project by Vector Green Sunshine Private Limited and Polepally Solar Parks Private Limited",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 70073,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1742",
      "resourceName": "Hydroelectric Project in Kinnaur District in Himachal Pradesh",
      "proponent": "Himachal Baspa Power Company Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 3541917,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "290",
      "resourceName": "Lee County Waste To Energy Facility 2007 Capital Expansion Project VCU",
      "proponent": "Lee County Board of County Commissioners SW Div.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Waste handling and disposal",
      "resourceStatus": "Registered",
      "country": "United States",
      "estAnnualEmissionReductions": 10864,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0025",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "913",
      "resourceName": "Siam Quality Starch Wastewater Treatment and Energy Generation Project in Chaiyaphum, Thailand",
      "proponent": "Siam Quality Starch Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Waste handling and disposal",
      "resourceStatus": "Registered",
      "country": "Thailand",
      "estAnnualEmissionReductions": 98372,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-08"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1741",
      "resourceName": "Yumrutepe Regulator and 15.013 MW Hydroelectric Power Plant Project",
      "proponent": "YUMRUTEPE ENERJI URETIM ANONIM SIRKETI",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 26224,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1740",
      "resourceName": "Reforestation with Teak  CO2e TEAKMEX",
      "proponent": "Agropecuaria Santa Genoveva S.A.P.I. de C.V.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Mexico",
      "estAnnualEmissionReductions": 16203,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-05"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "918",
      "resourceName": "BALKUSAN HYDROELECTRIC POWER PLANT",
      "proponent": "KAREN Kahramanmaraş Elektrik Üretim AŞ",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 58080,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "773",
      "resourceName": "8MW Waste Heat Recovery Based Power Project by Sree Rengaraaj Power India Private Limited",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Manufacturing industries",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 43179,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0012",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-02-01"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1739",
      "resourceName": "3 MW Hydro Power Project by Darjeeling Power Pvt. Ltd.",
      "proponent": "Darjeeling Power Pvt. Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 16404,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-01-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1736",
      "resourceName": "Grid connected electricity generation plant using natural gas at Jurong Island in Singapore",
      "proponent": "Pacificlight Power Pte. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Singapore",
      "estAnnualEmissionReductions": 57991,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0029",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-01-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1737",
      "resourceName": "Pampeana and Terra Santa Small Hydropower Plants Project Activity",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "Brazil",
      "estAnnualEmissionReductions": 25194,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-01-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1219",
      "resourceName": "Xinjiang Bazhou Haermodun 15MW Hydropower Project",
      "proponent": "Xinjiang Bazhou Xinhua Hydropower Development Co.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 66321,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-01-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1735",
      "resourceName": "Negros Island Solar Power Inc.",
      "proponent": "Negros Island Solar Power Inc.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Philippines",
      "estAnnualEmissionReductions": 66039,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-01-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1734",
      "resourceName": "Large scale grid connected solar PV Project in Toujounine (Nouakchott)",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Mauritania",
      "estAnnualEmissionReductions": 57141,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-01-08"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "92",
      "resourceName": "300MW Hydropower project by JHPL",
      "proponent": "Jaiprakash Hydro Power Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1052463,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-01-05"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1733",
      "resourceName": "Nouakchott 30 MW wind power plant",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Mauritania",
      "estAnnualEmissionReductions": 66438,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2017-12-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "381",
      "resourceName": "Bundled wind power project in Harshnath managed by Enercon (India)",
      "proponent": "Enercon (India) Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 12176,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2017-12-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "543",
      "resourceName": "Inner Mongolia Wuliji Wind Farm Project",
      "proponent": "CGN Wind Power CO.,Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 124076,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2017-12-22"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1732",
      "resourceName": "Kinik Wind Power Plant",
      "proponent": "Esinti Enerji Uretim Ticaret ve Sanayi Anonim Sirketi",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 90271,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2017-12-22"
    }
  ]
}

module.exports = {
  vcs
}