const vcs =
{
  totalCount: 2026,
  countExceeded: true,
  '@count': 2000,
  value: [
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2261',
      resourceName: 'CYY Biopower Wastewater treatment plant including biogas reuse for thermal oil replacement and electricity generation Project, Thailand.',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal, Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Thailand',
      estAnnualEmissionReductions: 84912,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0014',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-16'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2098',
      resourceName: 'Nanhai MSW Incineration II Project',
      proponent: 'Foshan Nanhai Green Renewable Energy Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal, Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 178556,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AM0025',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-13'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2259',
      resourceName: 'Royal Dairy Solid Separation Enhanced by Vermicomposting',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Livestock, enteric fermentation, and manure management',
      resourceStatus: 'Under development',
      country: 'United States',
      estAnnualEmissionReductions: 30000,
      region: 'North America',
      version: 'VCS Version 3',
      protocols: 'AMS-III.Y',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-13'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2260',
      resourceName: 'Shandong Laiwu Landfill Gas Recovery and Power Generation Project',
      proponent: 'Shandong Micropowers New Energy Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal, Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 35497,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D., AMS-III.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-13'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2257',
      resourceName: 'Wind Power Project by M/s D. J. Malpani at Jath in Maharashtra',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 33637,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-12'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1090',
      resourceName: 'Solar PV power project by Roha Dyechem Pvt.  Ltd. (EKIESL.CDM.Aug-11-02)',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 36367,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-05'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2097',
      resourceName: 'Tepekisla Dam & Hydropower Plant Project',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Turkey',
      estAnnualEmissionReductions: 114337,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-04'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '887',
      resourceName: 'Guangxi Youjiang Naji Navigation and Power Generatoin Project',
      proponent: 'Hightrack International (Hong Kong) Technology Lim',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 133779,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-03-02'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2095',
      resourceName: 'Duzce Aksu Hydro Electricity Power Plant',
      proponent: 'Bereket Enerji Uretim San ve Tic A.S',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Turkey',
      estAnnualEmissionReductions: 75382,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-28'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2096',
      resourceName: 'Akbas Hydroelectric Power Plant',
      proponent: 'Arı Su Enerji Üretim A.Ş.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Turkey',
      estAnnualEmissionReductions: 24574,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-28'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2094',
      resourceName: 'Koclu Regulator and Hydroelectric Power Plant (Koçlu Regulator & HEPP)',
      proponent: 'IYON ENERJI URETIMI SANAYI VE TICARET A.S.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Turkey',
      estAnnualEmissionReductions: 65024,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2252',
      resourceName: 'Rio Anapu-Pacaja REDD Project',
      proponent: 'Brazil AgFor LLC',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'Brazil',
      estAnnualEmissionReductions: 938000,
      region: 'Latin America',
      version: 'VCS Version 3',
      protocols: 'VM0015',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2093',
      resourceName: 'Waste to Energy Projects by Mahindra Waste to Energy Solutions Limited',
      proponent: 'MAHINDRA WASTE TO ENERGY SOLUTIONS LTD.',
      operator: null,
      designee: null,
      protocolCategories: 'Waste handling and disposal',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 38617,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0022',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-24'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2091',
      resourceName: 'AKKENT-ÇALKUYUCAK HYDROELECTRIC POWER PLANT',
      proponent: 'DNZ ELEKTRİK ÜRETIM A.Ş.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Turkey',
      estAnnualEmissionReductions: 21534,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-18'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2092',
      resourceName: 'Kirazlık Hydroelectric  Power Plant Project',
      proponent: 'Baren Enerji Sanayi ve Ticaret Üretim A.Ş.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Turkey',
      estAnnualEmissionReductions: 81307,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-18'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2090',
      resourceName: 'Wind Electricity Generation Project',
      proponent: 'Credits transferred from approved GHG program',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Credits Transferred from Approved GHG Program',
      country: 'India',
      estAnnualEmissionReductions: 80937,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-14'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2088',
      resourceName: 'Mangrove Restoration and Sustainable Development in Myanmar',
      proponent: 'Worldview International Foundation',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Myanmar',
      estAnnualEmissionReductions: 470954,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AR-AM0014',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-13'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2089',
      resourceName: 'Rio Taquesi Hydroelectric Power Project',
      proponent: 'Credits transferred from approved GHG program',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Credits Transferred from Approved GHG Program',
      country: 'Bolivia',
      estAnnualEmissionReductions: 191422,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-13'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2251',
      resourceName: 'PROYECTO REDD+ DE LOS PUEBLOS INDÍGENAS DEL VAUPÉS YUTUCU Y OTROS',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under validation',
      country: 'Colombia',
      estAnnualEmissionReductions: 348270,
      region: null,
      version: 'VCS Version 3',
      protocols: 'VM0015',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-12'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '803',
      resourceName: '9 MW grid connected bundled wind electricity generation project at Tirunelveli, Tamilnadu',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 23189,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-10'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2087',
      resourceName: 'Chudu Afforestation Project',
      proponent: 'Xichuan Rongda Agriculture and Forestry Co., Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 668883,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-02-10'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2085',
      resourceName: 'Revegetation with fruit Trees in North Manica Province, Mozambique',
      proponent: 'Agrimoz S.a r.l.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registered',
      country: 'Mozambique',
      estAnnualEmissionReductions: 30799,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-30'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2083',
      resourceName: 'Liangdu Afforestation Project',
      proponent: 'Guizhou Xinzhanxin Agricultural Technology Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 336390,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-29'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2084',
      resourceName: 'CONSERVATION PROJECT REDD+ SUR DEL META BOSQUES DE PAZ, SUSTENTO DE VIDA',
      proponent: 'ALLCOT AG',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Colombia',
      estAnnualEmissionReductions: 1334829,
      region: null,
      version: 'VCS Version 3',
      protocols: 'VM0015',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-29'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2082',
      resourceName: 'Qianbei Afforestation Project',
      proponent: 'Guizhou Xinzhanxin Agricultural Technology Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 708123,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-24'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2249',
      resourceName: 'HENAN FANGCHENG AND TANGHE AFFORESTATION PROJECT',
      proponent: 'Beijing Qianyuhui International Environmental Investment Co., Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'China',
      estAnnualEmissionReductions: 410771,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2242',
      resourceName: 'Installation of wind power project in Rajasthan and Tamil Nadu',
      proponent: 'Lalpur Wind Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration and verification approval requested',
      country: 'India',
      estAnnualEmissionReductions: 92328,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2243',
      resourceName: 'Wind power project in Madhya Pradesh, India',
      proponent: 'Lalpur Wind Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration and verification approval requested',
      country: 'India',
      estAnnualEmissionReductions: 40546,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2244',
      resourceName: 'Lalpur wind farm in Gujarat',
      proponent: 'Lalpur Wind Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration and verification approval requested',
      country: 'India',
      estAnnualEmissionReductions: 99859,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2245',
      resourceName: 'Wind power project in Rajasthan, India',
      proponent: 'Lalpur Wind Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration and verification approval requested',
      country: 'India',
      estAnnualEmissionReductions: 40546,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2246',
      resourceName: 'Nallakonda wind farm in Andhra Pradesh',
      proponent: 'Lalpur Wind Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 100630,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2247',
      resourceName: 'Tadas Wind Farm in Karnataka',
      proponent: 'Lalpur Wind Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 181436,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2248',
      resourceName: 'Wind energy project by LWEPL-1',
      proponent: 'Lalpur Wind Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration and verification approval requested',
      country: 'India',
      estAnnualEmissionReductions: 101865,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-15'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '744',
      resourceName: 'Pawan Urja Vistaran: Small entities combined wind power project in India - 2008',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 17415,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-14'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2080',
      resourceName: 'Jiro Kanto rural hydro-electricity in Alaotra-Mangoro',
      proponent: 'BETC Nanala',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Madagascar',
      estAnnualEmissionReductions: 12748,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.L.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-09'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '185',
      resourceName: 'Fuel-Switching Project from Fossil Fuels to Biomass in La Providencia, Arcor',
      proponent: 'Arcor Group',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Manufacturing industries',
      resourceStatus: 'Registered',
      country: 'Argentina',
      estAnnualEmissionReductions: 41700,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AM0036',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-07'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2079',
      resourceName: 'Fazenda Nascente do Luar Agroforestry Project',
      proponent: 'CARBON CREDITS CONSULTING S.R.L.',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registered',
      country: 'Brazil',
      estAnnualEmissionReductions: 22797,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-06'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '817',
      resourceName: 'Datong River Zhuchaxia Hydropower Station',
      proponent: 'GEPIC Darong Electric Power Company Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 121617,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-03'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2077',
      resourceName: 'TUIK RUCH LEW IMPROVED COOKSTOVE PROJECT FOR LAKE ATITLAN',
      proponent: "Asociación Tu'ik Ruch Lew",
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Registered',
      country: 'Guatemala',
      estAnnualEmissionReductions: 1707,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-II.G.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2020-01-02'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '823',
      resourceName: 'Datong River Tianwanggou Hydropower Station',
      proponent: 'GEPIC Darong Electric Power Company Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 179797,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-31'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2240',
      resourceName: 'N/A',
      proponent: 'Southern Power Company',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'United States',
      estAnnualEmissionReductions: 0,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-30'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1301',
      resourceName: 'Guohua  Rongcheng Phase ll Wind Farm Project',
      proponent: 'Guohua Resourceful Wind Power Generation Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 97240,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-30'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2239',
      resourceName: 'Akbas Hydroelectric Power Plant -DUPLICATE',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'Turkey',
      estAnnualEmissionReductions: 24574,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-29'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2076',
      resourceName: 'EOLO Wind Power Project',
      proponent: 'Credits transferred from approved GHG program',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Nicaragua',
      estAnnualEmissionReductions: 110054,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-23'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2238',
      resourceName: 'Duzce Aksu Hydro Electricity Power Plant - DUPLICATE (replaced by VCSR1815)',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'Turkey',
      estAnnualEmissionReductions: 75382,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-23'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '264',
      resourceName: 'Kargilik 24 MW Hydropower Plant, Turkey',
      proponent: 'Tektuð Elektrik Üretim A.Þ.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Turkey',
      estAnnualEmissionReductions: 40528,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-17'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '598',
      resourceName: 'Keban 5 MW Hydropower Plant, Turkey',
      proponent: 'Tektuð Elektrik Üretim A.Þ.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Turkey',
      estAnnualEmissionReductions: 19853,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-17'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1362',
      resourceName: 'Shandan Dongle Beitan 50MW Solar Power Generation Project',
      proponent: 'Shandan Xiehe Solar power generation Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 64743,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-16'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1406',
      resourceName: 'Jingyuan County 100MW Solar Power Generation Project',
      proponent: 'Gansu Deyou Energy Technology Co., Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 128589,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-16'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2075',
      resourceName: 'Agricultural Land Management Project in Hujgal & Kalari Cluster watershed, India implemented by Godrej Agrovet Ltd.',
      proponent: 'Godrej Agrovet Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 30403,
      region: null,
      version: 'VCS Version 3',
      protocols: 'VM0017',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-13'
    }
  ]
}

module.exports = {
  vcs
}
