const vcs = {
  totalCount: 2026,
  countExceeded: true,
  '@count': 2000,
  value: [
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2071',
      resourceName: 'COCOMACIA COMMUNITY REDD+ PROGRAM, CHOCO/ANTIOQUIA COLOMBIA',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Under development',
      country: 'Colombia',
      estAnnualEmissionReductions: 3073861,
      region: null,
      version: 'VCS Version 3',
      protocols: 'VM0006',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-06'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2072',
      resourceName: 'UK CowCredit project: A UK dairy initiative to reduce methane from enteric fermentation',
      proponent: 'MOOTRAL SA',
      operator: null,
      designee: null,
      protocolCategories: 'Livestock, enteric fermentation, and manure management',
      resourceStatus: 'Registration and verification approval requested',
      country: 'United Kingdom',
      estAnnualEmissionReductions: 187563,
      region: null,
      version: 'VCS Version 3',
      protocols: 'Methodology Under Development',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-06'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2073',
      resourceName: 'Electric Vehicle Charger Premier Aggregation',
      proponent: 'Connecticut Green Bank',
      operator: null,
      designee: null,
      protocolCategories: 'Transport',
      resourceStatus: 'Registered',
      country: 'United States',
      estAnnualEmissionReductions: 93097,
      region: null,
      version: 'VCS Version 3',
      protocols: 'VM0038',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-06'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2070',
      resourceName: 'Guinan Afforestation Project',
      proponent: 'Guizhou Baiheng Fertiliser Co., Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Agriculture Forestry and Other Land Use',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 645768,
      region: 'Asia',
      version: 'VCS Version 3',
      protocols: 'AR-ACM0003',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-04'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '621',
      resourceName: 'Biomass based renewable energy project in a Solvent Extraction Plant, India',
      proponent: 'M/s. Ambika Solvex Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 25476,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.C.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-12-04'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2069',
      resourceName: 'Greenfield Solar Power Mission by Fortum India',
      proponent: 'Fortum Solar Plus Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 412674,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-29'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1356',
      resourceName: 'Jiangsu Dongtai Phase II Wind Power Project',
      proponent: 'Guohua (Jiangsu) Wind Power Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 338010,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-28'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1200',
      resourceName: 'Guohua Wulate Zhongqi Chuanjing Phase II Wind Farm Project',
      proponent: 'Guohua Bayannaoer (Wulate Zhongqi) Wind  Power Co.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 62000,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-28'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '1196',
      resourceName: 'Gansu Yongdeng Longlin Hydro Power Project',
      proponent: 'Gansu Longlin Hydropower Development Co., Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 33525,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2065',
      resourceName: 'Renewable Energy Power Projects by Atria Power',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 314814,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2066',
      resourceName: 'PEBSA II-Del Bicentenario II Wind Farm',
      proponent: 'PEBSA',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'Argentina',
      estAnnualEmissionReductions: 56325,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2067',
      resourceName: 'Rao Trang Hydro Power 4 & 3',
      proponent: 'Rao Trang Hydropower Joint Stock Company',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'Viet Nam',
      estAnnualEmissionReductions: 32719,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2068',
      resourceName: 'Solar PV Greenfield project by Azure India',
      proponent: 'Azure Power Forty three Pvt. Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 525498,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-27'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2056',
      resourceName: 'Bundled Energy Efficiency Improvement Measures In Motor Systems by HZL',
      proponent: 'Hindustan Zinc Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy demand',
      resourceStatus: 'Registration requested',
      country: 'India',
      estAnnualEmissionReductions: 27262,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0012',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2057',
      resourceName: 'Renewable Solar Power Project By SolarArise India Project Pvt. Ltd.',
      proponent: 'SolarArise India Projects Pvt. Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'India',
      estAnnualEmissionReductions: 175918,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2058',
      resourceName: '50MW Greenfield Solar Plant in UP by Jakson Group',
      proponent: 'Jakson Power Pvt. Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'India',
      estAnnualEmissionReductions: 85873,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2059',
      resourceName: 'Renewable Solar Power Project by Mahindra Renewables Private Limited',
      proponent: 'Mahindra Renewables Private Limited.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 389911,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2060',
      resourceName: 'Suba and Usaquen Hydroelectric Umbrella Project',
      proponent: 'Empresa de Acueducto y Alcantarillado de Bogota E.S.P',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Colombia',
      estAnnualEmissionReductions: 10424,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2061',
      resourceName: 'Diadema II Wind Farm',
      proponent: 'E G Wind S.A.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Argentina',
      estAnnualEmissionReductions: 57872,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2062',
      resourceName: 'West Huaybong 2 wind farm project',
      proponent: 'K.R. Two Company Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'Thailand',
      estAnnualEmissionReductions: 131141,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2063',
      resourceName: 'El Mataco y San Jorge Wind Farm',
      proponent: 'Luz de Tres Picos',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'Argentina',
      estAnnualEmissionReductions: 445884,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2064',
      resourceName: 'Renewable Solar Power Project by Torrent Power',
      proponent: 'Torrent Power Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 92075,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '813',
      resourceName: 'Inner Mongolia Chifeng Gaofeng Wind Power Project',
      proponent: 'Chifeng Xinsheng Wind Power Co., Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'China',
      estAnnualEmissionReductions: 150915,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-26'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2048',
      resourceName: 'Kunming Shilin Grid-connected Solar Power Generation Project',
      proponent: 'Huaneng Shilin Photovolt Energy Development Co.,Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'China',
      estAnnualEmissionReductions: 105093,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2049',
      resourceName: 'Huaneng Daqing Aobao Wind Farm Project',
      proponent: 'Daqing Lvyuan Wind Power Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'China',
      estAnnualEmissionReductions: 116600,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2050',
      resourceName: 'Huaneng Gansu Guazhou Ganhekou No.2 Wind Farm Project',
      proponent: 'Huaneng Power International, Inc.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'China',
      estAnnualEmissionReductions: 408376,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2051',
      resourceName: '1944 MW SUDAIR SOLAR PROJECT',
      proponent: 'South Pole Carbon Asset Management Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Saudi Arabia',
      estAnnualEmissionReductions: 3374490,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2052',
      resourceName: 'Renewable Wind Power Project by Axis Wind Farms (Rayalaseema) Pvt. Ltd',
      proponent: 'Axis Wind Farms (Rayalaseema) Pvt. Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 202492,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2053',
      resourceName: 'Smart Anatolia Bundled Solar Project',
      proponent: 'SMART HOLDING A.S.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Turkey',
      estAnnualEmissionReductions: 26420,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2054',
      resourceName: 'Installation of 240 MW Hydroelectric Project at Kutehr in the Chamba district of Himachal Pradesh by JSW Energy',
      proponent: 'JSW Energy Kutehr Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 873698,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2055',
      resourceName: 'Shaoguan City Shaoneng Biomass Power Generation Project',
      proponent: 'Guangdong Shaoneng Group Co.,Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'China',
      estAnnualEmissionReductions: 190158,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0018',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-25'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2041',
      resourceName: '123 MW SOLAR PV IPP PROJECT ON LANDFILL IN BAHRAIN',
      proponent: 'South Pole Carbon Asset Management Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Bahrain',
      estAnnualEmissionReductions: 203808,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2042',
      resourceName: 'Renewable Wind Power Project by Adani',
      proponent: 'Adani Green Energy Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'India',
      estAnnualEmissionReductions: 172333,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2043',
      resourceName: 'Renewable Solar Power Project by Adani',
      proponent: 'Adani Green Energy Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 437825,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2044',
      resourceName: 'Renewable Wind Power Project by Torrent Power',
      proponent: 'Torrent Power Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 1709859,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2045',
      resourceName: 'Huaneng Tuokexun Baiyanghe First Stage 49.5MW wind farm project',
      proponent: 'Huaneng Tulufan Wind Power Generation Company Ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'China',
      estAnnualEmissionReductions: 98699,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2046',
      resourceName: '200 MW Kom Ombo Solar PV Power Project In Egypt',
      proponent: 'ACWA Power Komombo for Energy',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Egypt',
      estAnnualEmissionReductions: 340821,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2047',
      resourceName: '20 MW Capacity Biomass based Power Project of M/s. SHALIVAHANA GREEN ENERGY LIMITED',
      proponent: 'Shalivahana Green Energy Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Under development',
      country: 'India',
      estAnnualEmissionReductions: 87446,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0018',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-22'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2031',
      resourceName: 'ReNew Power bundled Wind Project',
      proponent: 'ReNew Power Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'India',
      estAnnualEmissionReductions: 984764,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2032',
      resourceName: '300 MW Solar Project by Avaada in Gujarat (India)',
      proponent: 'Avaada Sunrise Energy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'India',
      estAnnualEmissionReductions: 512196,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2033',
      resourceName: '3.5 MW Small Hydro Project In Himachal Pradesh',
      proponent: 'Gaur Hydro Power Pvt. ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'India',
      estAnnualEmissionReductions: 14462,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2034',
      resourceName: 'IBRI II Solar Independent Power Project',
      proponent: 'Shams Ad-Dhahira Generating Company SAOC',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Oman',
      estAnnualEmissionReductions: 1125184,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2035',
      resourceName: 'Solar Power Project by Renew Solar Power Private Limited',
      proponent: 'ReNew Solar Power Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'India',
      estAnnualEmissionReductions: 758268,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2036',
      resourceName: 'OUARZAZATE IV CONCENTRATED SOLAR POWER PROJECT',
      proponent: 'Numerco Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Morocco',
      estAnnualEmissionReductions: 150272,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2037',
      resourceName: 'Bundled Solar PV Rooftop Project by MAS - Phase I',
      proponent: 'Multiple Proponents',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Sri Lanka',
      estAnnualEmissionReductions: 15090,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2038',
      resourceName: 'Energising Indian homes by Solar rooftop projects',
      proponent: 'Azure Power India Pvt ltd',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'India',
      estAnnualEmissionReductions: 140874,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2039',
      resourceName: 'Badamsha 2 Wind Farm in Kazakhstan',
      proponent: 'Eni S.p.A.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registered',
      country: 'Kazakhstan',
      estAnnualEmissionReductions: 172580,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2040',
      resourceName: 'Vinh Hao 6 Solar Power Project',
      proponent: 'Vinh Hao 6 Power Joint Stock Company',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'Viet Nam',
      estAnnualEmissionReductions: 83750,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-21'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2022',
      resourceName: 'Huaneng Daqing Wukeshu Wind Farm Project',
      proponent: 'Daqing Lvyuan Wind Power Co., Ltd.',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Withdrawn',
      country: 'China',
      estAnnualEmissionReductions: 115536,
      region: null,
      version: 'VCS Version 3',
      protocols: 'ACM0002',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-20'
    },
    {
      program: 'Verified Carbon Standard',
      resourceIdentifier: '2023',
      resourceName: 'Renewable Solar Power Project By Rishabh Renergy',
      proponent: 'Rishabh Renergy Private Limited',
      operator: null,
      designee: null,
      protocolCategories: 'Energy industries (renewable/non-renewable sources)',
      resourceStatus: 'Registration requested',
      country: 'India',
      estAnnualEmissionReductions: 23089,
      region: null,
      version: 'VCS Version 3',
      protocols: 'AMS-I.D.',
      compatibleProgramScenarioTypeName: null,
      createDate: '2019-11-20'
    }
  ]
}

module.exports = {
  vcs
}
