const vcs = {
  "totalCount": 2026,
  "countExceeded": true,
  "@count": 2000,
  "value": [
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2024",
      "resourceName": "Nam Si Luong 1 hydropower project",
      "proponent": "Nam Si Luong 1 Hydropower Joint Stock Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Viet Nam",
      "estAnnualEmissionReductions": 97992,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2025",
      "resourceName": "Huaneng Tuokexun Baiyanghe Third Stage 49.5MW Wind Farm Project",
      "proponent": "Huaneng Tulufan Wind Power Generation Company Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 94121,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2026",
      "resourceName": "Allain Duhangan Hydroelectric Project (ADHP)",
      "proponent": "AD Hydro Power Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration and verification approval requested",
      "country": "India",
      "estAnnualEmissionReductions": 494668,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2027",
      "resourceName": "Bundled Solar Power Project by Hindustan Zinc Limited",
      "proponent": "Hindustan Zinc Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 77649,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2028",
      "resourceName": "100 MW Solar Project by Avaada in UP (India)",
      "proponent": "Avaada Non-Conventional UPProject Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 185303,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2029",
      "resourceName": "Huaneng Daqing Heping Wind Farm Project",
      "proponent": "Daqing Lvyuan Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "China",
      "estAnnualEmissionReductions": 115860,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2030",
      "resourceName": "Huaneng Daqing Xinli Wind Farm Project",
      "proponent": "Daqing Lvyuan Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 115397,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2009",
      "resourceName": "Renewable Energy Generation at Hamira",
      "proponent": "Enen Green Services Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 116832,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2010",
      "resourceName": "Fujian Pucheng IFM (conversion of logged to protected forest) Project",
      "proponent": "Zhejiang Zhongtuo Environmental Technology Development Co.,Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under development",
      "country": "China",
      "estAnnualEmissionReductions": 266253,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0010",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2011",
      "resourceName": "Huaneng Liaoning Fuxin Phase II Wind Farm Project",
      "proponent": "Huaneng New Energy Industrial Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 659993,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2012",
      "resourceName": "Liaoning Fuxin Gaoshanzi 100.5MW Wind Power Project",
      "proponent": "Huaneng New Energy Industrial Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 220542,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2013",
      "resourceName": "Jilin Tongyu Huaneng 100.5MW Wind Power Project",
      "proponent": "Huaneng New Energy Industrial Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "China",
      "estAnnualEmissionReductions": 253287,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2014",
      "resourceName": "50 MW SOLAR PROJECT BY AVAADA IN UP (INDIA)",
      "proponent": "Avaada Non-Conventional UPProject Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 90941,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2015",
      "resourceName": "Renewable Solar Photovoltaic Project by ACME Group",
      "proponent": "ACME Cleantech Solutions Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 3906661,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2016",
      "resourceName": "Grouped Solar Projects in Jordan",
      "proponent": "South Pole Carbon Asset Management Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Jordan",
      "estAnnualEmissionReductions": 39475,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2017",
      "resourceName": "Karnataka Pavagada-II Solar Project by Avaada (150 MW)",
      "proponent": "Avaada Solarise Energy Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 305870,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2018",
      "resourceName": "Santana Renewable Energy",
      "proponent": "Alianca Geracao de Energia S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 241485,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2019",
      "resourceName": "100 MW grid connected Wind Power project in Jamnagar Gujarat, India",
      "proponent": "Verdant Renewables Pvt Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 363796,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2020",
      "resourceName": "250 MW Wind Power Project by Mytrah Energy",
      "proponent": "M/s Mytrah Vayu (Sabarmati) Pvt. Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 506370,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2021",
      "resourceName": "Gravier Renewable Energy1",
      "proponent": "Alianca Geracao de Energia S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 124580,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "537",
      "resourceName": "Wind based renewable energy project in Gujarat",
      "proponent": "CLP India Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 107173,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2003",
      "resourceName": "Benban Solar PV Project Plot 3_1",
      "proponent": "Alcom Energy",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Egypt",
      "estAnnualEmissionReductions": 85879,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2004",
      "resourceName": "Ouarzazate II Concentrated Solar Power Project",
      "proponent": "Numerco Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Morocco",
      "estAnnualEmissionReductions": 406293,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2005",
      "resourceName": "OUARZAZATE III CONCENTRATED SOLAR POWER PROJECT",
      "proponent": "Numerco Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Morocco",
      "estAnnualEmissionReductions": 406293,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2006",
      "resourceName": "West Huaybong 3 wind farm project",
      "proponent": "First Korat Wind Company Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "Thailand",
      "estAnnualEmissionReductions": 139035,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2007",
      "resourceName": "Benban Solar PV Project Plot 43_4",
      "proponent": "Acwa Ben Ban one for Energy",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Egypt",
      "estAnnualEmissionReductions": 83683,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2008",
      "resourceName": "Benban Solar PV Project Plot 42_4",
      "proponent": "Numerco Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Egypt",
      "estAnnualEmissionReductions": 34914,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1997",
      "resourceName": "TROPICAL WIND IN THAILAND",
      "proponent": "Tropical Wind Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Thailand",
      "estAnnualEmissionReductions": 162898,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1998",
      "resourceName": "Cerro Dominador Concentrated Solar Power Project",
      "proponent": "CERRO DOMINADOR CSP S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Chile",
      "estAnnualEmissionReductions": 640313,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1999",
      "resourceName": "KRISSANA WIND POWER IN THAILAND",
      "proponent": "Krissana Wind Power Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Thailand",
      "estAnnualEmissionReductions": 143153,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2000",
      "resourceName": "K.R.S. THREE IN THAILAND",
      "proponent": "KRS Three Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Thailand",
      "estAnnualEmissionReductions": 157065,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2001",
      "resourceName": "K.R. ONE IN THAILAND",
      "proponent": "KR One Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Thailand",
      "estAnnualEmissionReductions": 148089,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "2002",
      "resourceName": "THEPARAK WIND IN THAILAND",
      "proponent": "Theparak Wind Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Thailand",
      "estAnnualEmissionReductions": 156167,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "800",
      "resourceName": "10.30 MW Grouped Wind Power Project in India.",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 16666,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1996",
      "resourceName": "GENNEIA SOLAR PROJECTS IN  ARGENTINA",
      "proponent": "GENNEIA S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Argentina",
      "estAnnualEmissionReductions": 85157,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-13"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1991",
      "resourceName": "WASTE HEAT RECOVERY-BASED POWER GENERATION PROJECTS BY HZL, IN INDIA",
      "proponent": "Hindustan Zinc Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 42510,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.Q",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1992",
      "resourceName": "ENERGY EFFICIENCY IN STEAM TURBINE GENERATOR SYSTEMS BY HZL",
      "proponent": "Hindustan Zinc Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 63138,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-II.B.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1993",
      "resourceName": "Bundled Wind Power project in Koppal Karnataka",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 266634,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1994",
      "resourceName": "PEBSA-Del Bicentenario Wind Farm",
      "proponent": "PEBSA",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Argentina",
      "estAnnualEmissionReductions": 225298,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1995",
      "resourceName": "Folha Larga Sul Renewable Energy",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Brazil",
      "estAnnualEmissionReductions": 332753,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1985",
      "resourceName": "100 MW Bundled Wind Power Project in Anantapuram, Andhra Pradesh",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 192849,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1986",
      "resourceName": "13 MW Grid Connected Dandela Mini Hydel Scheme, Karnataka State, India.",
      "proponent": "Sagar Power Dandela Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 32160,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1987",
      "resourceName": "GENNEIA WIND PROJECTS IN ARGENTINA",
      "proponent": "GENNEIA S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Argentina",
      "estAnnualEmissionReductions": 699147,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1988",
      "resourceName": "GHG Capture in the Production of Plastic Materials",
      "proponent": "Newlight Technologies",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy demand",
      "resourceStatus": "Under development",
      "country": "United States",
      "estAnnualEmissionReductions": 32205,
      "region": null,
      "version": "VCS Version 3",
      "protocols": null,
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1989",
      "resourceName": "Oualidia 1&2 Wind Projects",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Morocco",
      "estAnnualEmissionReductions": 54114,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1990",
      "resourceName": "40 MW Bundled Solar Project in Telangana, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 79241,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1984",
      "resourceName": "40 MW Bundled Solar Project in Telangana, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "India",
      "estAnnualEmissionReductions": 79241,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-08"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1983",
      "resourceName": "Guangdong Taishan Shangchuandao Island Phase II Wind Farm Project",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 28813,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1979",
      "resourceName": "10 MW biomass based power generation project at Wani, Yavatmal by Shalivahana Projects Limited",
      "proponent": "Shalivahana Green Energy Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 48132,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1980",
      "resourceName": "24 MW Chayadevi Mini Hydro power project in Karnataka, India",
      "proponent": "Bhoruka Power Corporation Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 42419,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-06"
    }
  ]
}

module.exports = {
  vcs
}
