const vcs = {
  "totalCount": 2026,
  "countExceeded": true,
  "@count": 2000,
  "value": [
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1981",
      "resourceName": "Waste Heat Recovery Power Project at JK Cement Works (Unit of JK Cement Limited), Nimbahera, Chittorgarh, Rajasthan",
      "proponent": "JK Cement Ltd. (JKCL)",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 70796,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0012",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1982",
      "resourceName": "Ngodwana Biomass to Energy Project",
      "proponent": "Ngodwana Energy (Pty) Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "South Africa",
      "estAnnualEmissionReductions": 188150,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0018",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1976",
      "resourceName": "Renewable Solar Power Project by Shapoorji Pallonji",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 432770,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-04"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1978",
      "resourceName": "Malleco, Lomas de Duqueco and Negrete Wind Project, Chile",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Chile",
      "estAnnualEmissionReductions": 699147,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-04"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1973",
      "resourceName": "Huaneng Tongyu Tuanjie Phase E Wind Farm Project",
      "proponent": "Huaneng Jilin Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 103905,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-01"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1974",
      "resourceName": "Srepok 1 Solar Power Project",
      "proponent": "Dai Hai Power Development and Invesment Joint Stock Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Viet Nam",
      "estAnnualEmissionReductions": 64206,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-01"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1975",
      "resourceName": "Hong Phong 4 Solar 48 MW Project",
      "proponent": "name  Ha Do Binh Thuan Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Viet Nam",
      "estAnnualEmissionReductions": 77400,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-11-01"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "202",
      "resourceName": "Bom Jesus Ceramic Fuel Switching Project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 9356,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.E.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-31"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1971",
      "resourceName": "SAKAL SOLAR FARM",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Senegal",
      "estAnnualEmissionReductions": 22270,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1972",
      "resourceName": "Guangxi Longan Biomass Power Project",
      "proponent": "Guangxi Deli New energy Technology Co. ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 95542,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1968",
      "resourceName": "Grid Connected Wind Energy Project in Gujarat",
      "proponent": "CLP India Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 759489,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1969",
      "resourceName": "The ARC A/R Project",
      "proponent": "Amazon Reforestation Consortium",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registration requested",
      "country": "Brazil",
      "estAnnualEmissionReductions": 516780,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1970",
      "resourceName": "Ventus Wind Farm in El Salvador",
      "proponent": "Ventus, S.A.de C.V",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "El Salvador",
      "estAnnualEmissionReductions": 103593,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "788",
      "resourceName": "China Guangdong Shenzhen Qianwan LNG generation project",
      "proponent": "Shenzhen Guangqian Electric Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 857072,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, AM0029",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1967",
      "resourceName": "Wind Power Project at Tamil Nadu, India",
      "proponent": "Shalivahana Green Energy Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 18786,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1965",
      "resourceName": "Cat Hiep Solar Power Project",
      "proponent": "Binh Dinh TTP Energy and High Technology Joint Stock Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Viet Nam",
      "estAnnualEmissionReductions": 59541,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1966",
      "resourceName": "Huaneng Gansu Huajialing 49.5MW Wind Power Project",
      "proponent": "Huaneng Huajialing Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "China",
      "estAnnualEmissionReductions": 91046,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "743",
      "resourceName": "Pawan Urja Vistaran: Small entities combined wind power project in India - 2007",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 53813,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1964",
      "resourceName": "Quang Minh Solar Power Project",
      "proponent": "Srepok Solar Power Joint Stock Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Viet Nam",
      "estAnnualEmissionReductions": 61524,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1961",
      "resourceName": "7 MW Hydel Based Power Unit on River Jatashankari, Chhattisgarh",
      "proponent": "Shalivahana Green Energy Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 22957,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1962",
      "resourceName": "Daan Laifu Wind Farm Phase II Project",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 109116,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1963",
      "resourceName": "Tataouine Solar Photovoltaic Plant in Tunisia",
      "proponent": "SEREE",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Tunisia",
      "estAnnualEmissionReductions": 14376,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1960",
      "resourceName": "Montana Improved Grazing Project",
      "proponent": "Native Energy, Inc.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under development",
      "country": "United States",
      "estAnnualEmissionReductions": 22000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0021",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1958",
      "resourceName": "My Son - Hoan Loc Viet Solar Energy Project",
      "proponent": "My Son Hoan Loc Viet Solar Energy Joint Stock Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Viet Nam",
      "estAnnualEmissionReductions": 65871,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1959",
      "resourceName": "Aussenkehr solar",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Namibia",
      "estAnnualEmissionReductions": 14673,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-10-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1955",
      "resourceName": "Jilin TongHua Biomass Power Project",
      "proponent": "Tonghua Xinneng Biomass Power Cogeneration Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 107078,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1956",
      "resourceName": "Shaanxi Chengcheng Biomass Power Project",
      "proponent": "Shaanxi Chengcheng Qinyao Power Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 118019,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1953",
      "resourceName": "The ARC REDD+ Project",
      "proponent": "Amazon Reforestation Consortium",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 340000,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "VM0015",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1954",
      "resourceName": "Badamsha Wind Farm in Kazakhstan",
      "proponent": "Eni S.p.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Kazakhstan",
      "estAnnualEmissionReductions": 172406,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1951",
      "resourceName": "HUANENG CHANGTU TAIPING WIND FARM PROJECT",
      "proponent": "Huaneng Changtu Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 102738,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1952",
      "resourceName": "Huaneng Tongyu Tuanjie Phase A Wind Farm Project",
      "proponent": "Huaneng Jilin Power Generation Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 96208,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1949",
      "resourceName": "Longyuan Mulilo De Aar Maanhaarberg Wind Energy Facility",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "South Africa",
      "estAnnualEmissionReductions": 286752,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1950",
      "resourceName": "Longyuan Mulilo De Aar 2 North Wind Energy Facility",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "South Africa",
      "estAnnualEmissionReductions": 433929,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "795",
      "resourceName": "Dalmia Chini Mills Nigohi Project",
      "proponent": "Dalmia Bharat Sugar and Industries Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 32795,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "809",
      "resourceName": "Wind power project by AL – Wind Energy in Tamilnadu",
      "proponent": "AL-Wind Energy",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 17561,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1947",
      "resourceName": "Inner Mongolia Wujier Phase I Wind Power Project",
      "proponent": "Inner Mongolia Xinjin Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 120508,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "275",
      "resourceName": "5MW Wind Mill Project of RBD by M/s. Rakesh Builders| Developers in Tirunelveli District, Tamil Nadu, India",
      "proponent": "RAKESH BUILDERS | DEVELOPERS",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 11147,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1946",
      "resourceName": "Renewable Wind Power Project by Hero Future Energies",
      "proponent": "Hero Future Energies Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 50140,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "168",
      "resourceName": "Bundled Wind Project Activity by M/s Bhagyanagar India Ltd and M/s Surana Telecom and Power Limited",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 21499,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1945",
      "resourceName": "MSA-1 Hydropower Plant",
      "proponent": "Araucania Power S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Chile",
      "estAnnualEmissionReductions": 10111,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1944",
      "resourceName": "Livelihoods Mount Elgon Project",
      "proponent": "Livelihoods Fund",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under validation",
      "country": "Kenya",
      "estAnnualEmissionReductions": 53142,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0017",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-04"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "392",
      "resourceName": "Gansu Datang Yumen 49 MW Wind Power Project",
      "proponent": "Gansu Datang Yumen Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 96969,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-09-03"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1943",
      "resourceName": "20MW Samal Grid-connected Hydroelectric Project in Orissa, India",
      "proponent": "Orissa Power Consortium Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 80126,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-29"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "424",
      "resourceName": "7.85 MW Bundled grid-connected wind electricity generation project in Tamil Nadu and Karnataka, India.",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 16800,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1942",
      "resourceName": "Renewable Solar Power Project by Hero Future Energies",
      "proponent": "Hero Future Energies Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "India",
      "estAnnualEmissionReductions": 601957,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1939",
      "resourceName": "CECEP Gansu Yumen Changma Daba South Wind Farm Project",
      "proponent": "CECEP Wind Power (Gansu) Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 91400,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1940",
      "resourceName": "CECEP Gansu Yumen Changma Daba North Wind Farm Project.",
      "proponent": "CECEP Wind Power (Gansu) Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 90531,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1941",
      "resourceName": "Sustainable City Projects at India’s Cleanest City- Indore",
      "proponent": "Indore Smart City Development Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal, Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 283396,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, AMS-I.D., ACM0022",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1937",
      "resourceName": "Song Lo 4 Hydropower Project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Viet Nam",
      "estAnnualEmissionReductions": 66757,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-23"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1936",
      "resourceName": "WIND POWER GROUPED PROJECT BY CELSIA COLOMBIA - BEGONIA POWER",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Colombia",
      "estAnnualEmissionReductions": 166385,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-20"
    }
  ]
}

module.exports = {
  vcs
}