const vcs = {
  "totalCount": 2026,
  "countExceeded": true,
  "@count": 2000,
  "value": [
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1935",
      "resourceName": "Hubei Hongshan IFM (Conversion of Logged to Protected Forest) Project",
      "proponent": "Zhejiang Zhongzheng Forestry Development Co.,Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 292309,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0010",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1934",
      "resourceName": "Patikari Hydro Electric Power Project in Distt-Mandi, Himachal Pradesh, India",
      "proponent": "Patikari Power Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 58583,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1933",
      "resourceName": "Mavibayrak Biomass Power Plant Project",
      "proponent": "Mavibayrak Enerji Uretim A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 35612,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0018",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1931",
      "resourceName": "Energising India using Solar Energy Projects",
      "proponent": "Azure Power India Pvt ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 684229,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "699",
      "resourceName": "Yiyang Xiushan Hydropower Project",
      "proponent": "TAOHUAJIANG ENERGY DEVELOPMENT CO., LTD",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 240000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "455",
      "resourceName": "Maraca Ceramic Fuel Switching Project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 12372,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.E.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "522",
      "resourceName": "Chile: Lircay Run-Of-River Project",
      "proponent": "Hidromaule S.A",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Chile",
      "estAnnualEmissionReductions": 53040,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0026",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1930",
      "resourceName": "Henan Nanzhao Afforestation Project",
      "proponent": "Beijing Pingtouge Forestry Carbon Technology Development Co.,Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 493806,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "383",
      "resourceName": "7.4 MW Bundled grid-connected wind electricity generation project, Tamil Nadu, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 17437,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "797",
      "resourceName": "Jingshan Kaidi Biomass Power Project",
      "proponent": "Jingshan Kaidi Green Energy Development Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 90446,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1929",
      "resourceName": "Electrify America - EV Charging Network Carbon Credits",
      "proponent": "Electrify America",
      "operator": null,
      "designee": null,
      "protocolCategories": "Transport",
      "resourceStatus": "Registered",
      "country": "United States",
      "estAnnualEmissionReductions": 7989,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0038",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-29"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1926",
      "resourceName": "Iota M. Firinci Solar Power Project",
      "proponent": "IOTA Gunes Enerjisi Elektrik Uretim ve Ticaret A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 8726,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1920",
      "resourceName": "24.45 MW Biomass based project in Punjab",
      "proponent": "Satia Industries Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 208613,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1921",
      "resourceName": "Van Solar Power Project",
      "proponent": "Omicron-PSI Enerji A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 33629,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1922",
      "resourceName": "Amasya Solar Power Project",
      "proponent": "Neptun Enerji A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "Turkey",
      "estAnnualEmissionReductions": 9356,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1923",
      "resourceName": "Yaysun-MT Solar Power Project",
      "proponent": "YAYSUN-MT Enerji A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 22906,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1924",
      "resourceName": "Tokat Solar Power Project",
      "proponent": "Bahceli Enerji A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 4765,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1925",
      "resourceName": "ME-SE Solar Power Project",
      "proponent": "ME-SE Enerji A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 10504,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "955",
      "resourceName": "Bundled Wind Energy Project in Indian States:- EnKing International 2006.",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 14345,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1919",
      "resourceName": "Adeco Agropecuaria S.A. Biogas Energy Generation from Dairy Production",
      "proponent": "Adeco Agropecuaria S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal, Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Argentina",
      "estAnnualEmissionReductions": 17405,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D., AMS-III.D., AMS-III.H.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1917",
      "resourceName": "AWMS GHG Mitigation Project MX05-B-03, Sonora, Mexico",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "Mexico",
      "estAnnualEmissionReductions": 1210095,
      "region": null,
      "version": "VCS Version 3",
      "protocols": null,
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1918",
      "resourceName": "Paradigm Kenya Clean Cookstoves Project",
      "proponent": "The Paradigm Project",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy demand",
      "resourceStatus": "Registered",
      "country": "Kenya",
      "estAnnualEmissionReductions": 49416,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-II.G.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1001",
      "resourceName": "Inner Mongolia Yihewusu Phase II 49.5 MW Wind Power Project",
      "proponent": "Inner Mongolia Xinjin Wind Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 67000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1916",
      "resourceName": "Quebec Forestry Sector Carbon Sequestration Grouped Project Pivot",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under validation",
      "country": "Canada",
      "estAnnualEmissionReductions": 115408,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0034",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1914",
      "resourceName": "150 MW Solar Project in Karnataka by Avaada Solar",
      "proponent": "Avaada Solar Energy Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 319470,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1915",
      "resourceName": "Ombepo Wind",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Namibia",
      "estAnnualEmissionReductions": 32464,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1913",
      "resourceName": "Erzurum Hinis Solar Power Plant",
      "proponent": "GalataWindEnerjiAS",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 7711,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "789",
      "resourceName": "Inner Mongolia Bayinxile Wind Power Project",
      "proponent": "China Resources Wind Power Inner Mongolia Bayinxil",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 130286,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-07-05"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1912",
      "resourceName": "Run-of-the-river Hydroelectric Power Project in Uttarakhand by Alaknanda Hydro Power Company Limited",
      "proponent": "Alaknanda Hydro Power Company Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 1204120,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1908",
      "resourceName": "Denizli Wind Power Project, Turkey",
      "proponent": "Korda Enerji Uretim Pazarlama Ithalat ve Ihracat A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 105524,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1909",
      "resourceName": "Santa Ana Hydroelectric Plant",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "Colombia",
      "estAnnualEmissionReductions": 20642,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1910",
      "resourceName": "Bionersis landfill project in Pasto, Colombia",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 54343,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0001",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1911",
      "resourceName": "King County Rural Forest Carbon Project",
      "proponent": "King County Department of Natural Resources, Water and Land Division",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "United States",
      "estAnnualEmissionReductions": 9195,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0012",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "386",
      "resourceName": "La Cascada 2.3 MW Hydroelectric Project",
      "proponent": "Prestadora de Servicios Públicos La Cascada SA ESP",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 5139,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1905",
      "resourceName": "Kocalar Wind Power Project",
      "proponent": "Isider Enerji Uretim Pazarlama Ithalat ve Ihracat A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 58064,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1906",
      "resourceName": "Hasanoba Wind Power Project",
      "proponent": "Kovanci Enerji Uretim Pazarlama Ithalat ve Ihracat A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 87209,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1907",
      "resourceName": "Üçpinar Wind Power Project",
      "proponent": "Derbent Enerji Uretim Pazarlama Ithalat ve Ihracat A.S.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Turkey",
      "estAnnualEmissionReductions": 180032,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1904",
      "resourceName": "Wind Power Project in Tamil Nadu by Green Infra Renewable Energy Limited",
      "proponent": "Green Infra Renewable Energy Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 707515,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1903",
      "resourceName": "VTRM Renewable Energy 2",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 439950,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1902",
      "resourceName": "Salvador da Bahia Landfill Gas Management Project",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "Brazil",
      "estAnnualEmissionReductions": 242950,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1900",
      "resourceName": "Makame Savannah REDD",
      "proponent": "Carbon Tanzania",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Tanzania",
      "estAnnualEmissionReductions": 136411,
      "region": "Africa",
      "version": "VCS Version 3",
      "protocols": "VM0007",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1901",
      "resourceName": "CECIC Zhangbei Gaojialiang Wind farm Project",
      "proponent": "CECIC Wind Power (Zhangbei) Yunwei Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "China",
      "estAnnualEmissionReductions": 89366,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1899",
      "resourceName": "Sumatra Merang Peatland Project (SMPP)",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Indonesia",
      "estAnnualEmissionReductions": 1338569,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "VM0007",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1897",
      "resourceName": "Ntakata Mountains REDD",
      "proponent": "Carbon Tanzania",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Tanzania",
      "estAnnualEmissionReductions": 420200,
      "region": "Africa",
      "version": "VCS Version 3",
      "protocols": "VM0007",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1898",
      "resourceName": "50 MW Tsetsii Wind Farm in Mongolia",
      "proponent": "Clean Energy Asia LLC",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Mongolia",
      "estAnnualEmissionReductions": 175767,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1895",
      "resourceName": "Jilin Linjiang Afforestation Project",
      "proponent": "Jilin Forest Industry Environmental Technology Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 546751,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1896",
      "resourceName": "Hunan Northern and Northwestern Area Afforestation Project",
      "proponent": "Jilin Forest Industry Environmental Technology Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registration requested",
      "country": "China",
      "estAnnualEmissionReductions": 286518,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-06-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1893",
      "resourceName": "18 MW Kemphole Mini Hydel Scheme (KMHS), by International Power Corporation Limited, India",
      "proponent": "International Power Corporation Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 44548,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-05-22"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1891",
      "resourceName": "Kishanganga Hydroelectric Project",
      "proponent": "NHPC Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1563247,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-05-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1892",
      "resourceName": "SOLAR GROUPED PROJECT BY EPSA-CELSIA",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 103799,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-05-21"
    }
  ]
}

module.exports = {
  vcs
}