const vcs = {
  "totalCount": 2026,
  "countExceeded": true,
  "@count": 2000,
  "value": [
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1890",
      "resourceName": "Grid Connected Solar Energy Project",
      "proponent": "CLP India Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 289503,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-05-03"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "722",
      "resourceName": "Guangdong Huizhou LNG Power Generation Project",
      "proponent": "Guangdong Huizhou LNG Power Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 630484,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0029",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-05-03"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1888",
      "resourceName": "Larimer County Landfill Gas Flaring Project",
      "proponent": "3Degrees Group, Inc",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal",
      "resourceStatus": "Registered",
      "country": "United States",
      "estAnnualEmissionReductions": 18637,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "Methodology Under Development",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1886",
      "resourceName": "Nanyang Danjiang River Solar Cooker Project Phase I",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 129914,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1887",
      "resourceName": "Nanyang Danjiang River Solar Cooker Project Phase II",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 93962,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1885",
      "resourceName": "Ejuva One and Ejuva Two Solar Projects",
      "proponent": "AERA Group",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Namibia",
      "estAnnualEmissionReductions": 26265,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1884",
      "resourceName": "Bikes for the Planet - Brazil",
      "proponent": "ZSCORE S. A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Transport",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 167,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.BM",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1882",
      "resourceName": "REDD+ PROJECT IN THE ALTO HUAYABAMBA CONSERVATION CONCESSION (CCAH).",
      "proponent": "Asociacion Amazonicos por la Amazonía",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Peru",
      "estAnnualEmissionReductions": 52425,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "VM0015",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1883",
      "resourceName": "Pichacay Landfill Gas Renewable Energy Project",
      "proponent": "EMAC-BGP ENERGY COMPANÍA DE ECONOMÍA MIXTA CEM",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal, Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Ecuador",
      "estAnnualEmissionReductions": 33237,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.G.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "447",
      "resourceName": "12.5 MW Bundled grid-connected wind electricity generation project in Karnataka, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 26905,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-04-04"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1881",
      "resourceName": "Conservation of Panama Forests - Reduction of GHG Emissions from Deforestation and forest Degradation. Grouped Project",
      "proponent": "Panamanian Pro Carbon Association",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under validation",
      "country": "Panama",
      "estAnnualEmissionReductions": 14126091,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0015",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1877",
      "resourceName": "Thangarabalu Small Hydel Project at Karnataka",
      "proponent": "Kare Power Resources Private Limited. (KPRPL)",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 53983,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1878",
      "resourceName": "Bundled renewable energy project in Gujarat and Karnataka, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 11842,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1879",
      "resourceName": "Adavikanda, Kuruwita Division Mini Hydro Power Project",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "Sri Lanka",
      "estAnnualEmissionReductions": 20000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1875",
      "resourceName": "Guangxi Fusui Qiquan biomass power generation project",
      "proponent": "Guangxi Fusui Qiquan biomass power generation Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 117822,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0018",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1239",
      "resourceName": "Utilization of Biomass in Bricks Manufacturing By Ozone Envirotech Pvt. Ltd. (OEPL)",
      "proponent": "Ozone Envirotech Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Manufacturing industries",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 42499,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.Z",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1870",
      "resourceName": "Gezin Solar Power Project",
      "proponent": "Lahit Elektrik Üretim A.S.and Petrojes Elektrik Üretim A.S. (bundled)",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 3952,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-13"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1872",
      "resourceName": "N2O ABATEMENT PROJECT AT AEL 11_",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Chemical industry",
      "resourceStatus": "Registered",
      "country": "South Africa",
      "estAnnualEmissionReductions": 269581,
      "region": null,
      "version": "VCS Version 3",
      "protocols": null,
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-13"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1873",
      "resourceName": "N2O ABATEMENT PROJECT AT AEL 9_",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Chemical industry",
      "resourceStatus": "Registered",
      "country": "South Africa",
      "estAnnualEmissionReductions": 93239,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0034",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-13"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1874",
      "resourceName": "Zhangjiakou Chabei Wind Farm Project",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "China",
      "estAnnualEmissionReductions": 203090,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-13"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1869",
      "resourceName": "Yagual - Carbon Sequestration Grouped Project for the Restoration, Conservation and Sustainable Production in the Guerrero, Sumapaz and Rabanal Paramo Systems",
      "proponent": "Société de gestion de projets ECOTIERRA Inc.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 13619,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1867",
      "resourceName": "Ningxia Xiangshan Wind Farm Project",
      "proponent": "Ningxia Zhongwei Aluminum New Energy Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 727982,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-08"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1868",
      "resourceName": "GUACHICONO SMALL HYDROELECTRIC PROJECT",
      "proponent": "GELEC GUACHICONO S.A.S .E.S.P",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Colombia",
      "estAnnualEmissionReductions": 20049,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-08"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1866",
      "resourceName": "XinJiang Makit County Afforestation Carbon Sequestration Project",
      "proponent": "Makit Base Junlian Cotton Industry Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 90393,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1864",
      "resourceName": "Puzhen Afforestation Project in Guizhou Province",
      "proponent": "Guizhou Baiheng Fertiliser Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 313023,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1865",
      "resourceName": "Xiguan Afforestation Project in Guizhou Province",
      "proponent": "Guizhou Baiheng Fertiliser Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 388420,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1863",
      "resourceName": "ENERGY EFFICIENCY COOK STOVE IMPLEMENTATION IN NEPAL",
      "proponent": "Enen Green Services Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy demand",
      "resourceStatus": "Registered",
      "country": "Nepal",
      "estAnnualEmissionReductions": 56811,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-II.G.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-05"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1364",
      "resourceName": "Hydroelectric Project PCH Luzma",
      "proponent": "Generadora Luzma S.A. E.S.P.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 99992,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-03-05"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1862",
      "resourceName": "Bundled Wind Power Project in Gujarat and Tamil Nadu",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 29987,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1052",
      "resourceName": "North Pikounda REDD+",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Congo",
      "estAnnualEmissionReductions": 231110,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0011",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1163",
      "resourceName": "Wind Power Project in Tirupur District",
      "proponent": "NSL WInd Power Company Phoolwadi Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 109306,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1861",
      "resourceName": "3.5MW Manuni Hydro Electric Project in Himanchal Pradesh by Winsome Textile Industries Ltd",
      "proponent": "Winsome Textile Industries Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 17619,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1859",
      "resourceName": "Heqing Solar Cooker Project II",
      "proponent": "Clean Air Trade, Inc.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 143762,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1860",
      "resourceName": "Heqing Solar Cooker Project I",
      "proponent": "Clean Air Trade, Inc.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 143762,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "700",
      "resourceName": "Wind power project at Tamilnadu by Powerica Limited",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 32956,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "701",
      "resourceName": "Wind power project at Gujarat by Powerica Limited",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 29443,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1210",
      "resourceName": "Green Energy Project at Kutch by Powerica Limited",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 53122,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1211",
      "resourceName": "Green Energy Project at Gujarat by Powerica Limited",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 61360,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "777",
      "resourceName": "8.6 MW Captive Wind Energy Project in Tamil Nadu",
      "proponent": "Loyal Textiles Mills Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 11976,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "391",
      "resourceName": "Gullubag 96 MW Hydro Electric Power Plant Project, Turkey",
      "proponent": "Senerji Enerji Uretim As",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 193000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-02-05"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1857",
      "resourceName": "Grouped OFF-GRID Renewable Energy Project in India",
      "proponent": "Swiss carbon Value Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 38366,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.F.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-31"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1856",
      "resourceName": "Bundled Wind Power Project by Sembcorp Green Infra Limited in India",
      "proponent": "Green Infra Wind Energy Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 191006,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1855",
      "resourceName": "Hechu Afforestation Project in Anhui Province",
      "proponent": "Hefei Zhuoya Landscaping Engineering Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 469187,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-23"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1854",
      "resourceName": "20 MWAC (22 MWDC) SKCIL SOLAR POWER PLANT PROJECT",
      "proponent": "Shri Keshav Cements & Infra Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 33707,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-22"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1853",
      "resourceName": "9.9 MW Wind Power Project by KPL International Ltd. in Gujarat",
      "proponent": "KPL International Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 24232,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1852",
      "resourceName": "Northern Fuel Pipeline Transportation Project, Thailand",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Transport",
      "resourceStatus": "Registration requested",
      "country": "Thailand",
      "estAnnualEmissionReductions": 29180,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "Methodology Under Development",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "794",
      "resourceName": "Dahao Wind Power Project",
      "proponent": "China Resources Windpower Development (Shantou Hao",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 40000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1851",
      "resourceName": "Renewable Solar Power Project by ReNew Solar Power Private Limited",
      "proponent": "ReNew Solar Power Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1767281,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2019-01-03"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1214",
      "resourceName": "Vajrakarur Wind Power Project in Andhra Pradesh",
      "proponent": "Mytrah Vayu (Pennar) Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 124363,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-31"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "728",
      "resourceName": "CECIC Gansu Yumen Changma No.3 Wind Farm Project",
      "proponent": "CECIC HKC Wind Power (Gansu) Co., LTD.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 425689,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-26"
    }
  ]
}

module.exports = {
  vcs
}