const vcs = {
  "totalCount": 2026,
  "countExceeded": true,
  "@count": 2000,
  "value": [
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1850",
      "resourceName": "Pesqueiro Energia Small Hydroelectric Project (PESHP)",
      "proponent": "Credits transferred from approved GHG program",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Credits Transferred from Approved GHG Program",
      "country": "Brazil",
      "estAnnualEmissionReductions": 17927,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1848",
      "resourceName": "Korea - Myanmar Joint - Bago District REDD+ Program, with North Zamari Wildlife Sanctuary",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under validation",
      "country": "Myanmar",
      "estAnnualEmissionReductions": 238397,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "VM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1849",
      "resourceName": "Ranchland Solar, LLC",
      "proponent": "Ranchland Solar, LLC",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "United States",
      "estAnnualEmissionReductions": 30267,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1847",
      "resourceName": "Qianxinan Afforestation Project in Guizhou Province",
      "proponent": "Guizhou Baiheng Fertiliser Co., Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 469669,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1845",
      "resourceName": "30 MW SOLAR BY AVAADA SUSTAINABLE ENERGY PVT LTD – HANAGAL.",
      "proponent": "Avaada Sustainable Energy Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "India",
      "estAnnualEmissionReductions": 43825,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1846",
      "resourceName": "30 MW SOLAR BY SOLARSYS NON CONVENTIONAL ENERGY PVT. LTD. - BANAVIKAL.",
      "proponent": "Solarsys Non conventional Energy Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "India",
      "estAnnualEmissionReductions": 43825,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1842",
      "resourceName": "100 MW SOLAR PROJECT IN BHADLA IN RAJASTHAN.",
      "proponent": "Clean Sustainable Energy Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 176539,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1843",
      "resourceName": "100 MW SOLAR BY GIRIRAJ RENEWABLES PVT. LTD.- SATARA.",
      "proponent": "Giriraj Renewables Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "India",
      "estAnnualEmissionReductions": 135329,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1844",
      "resourceName": "80 MW SOLAR BY FERMI SOLAR FARMS PVT LTD - CHALISGAON.",
      "proponent": "Fermi Solar Farms Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 154070,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "920",
      "resourceName": "IBERPAPEL SILVIPASTURAL SYSTEM ON DEGRADED LAND",
      "proponent": "Los Eucaliptus S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Uruguay",
      "estAnnualEmissionReductions": 14746,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-ACM0001",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1841",
      "resourceName": "Santa Teresa Hydropower Plant",
      "proponent": "INLAND ENERGY SAC",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Peru",
      "estAnnualEmissionReductions": 293121,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "410",
      "resourceName": "6.85 MW Bundled grid-connected wind electricity generation project in Tamil Nadu and Karnataka, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 16634,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1840",
      "resourceName": "Ovejería Photovoltaic Power Plant",
      "proponent": "Colbun S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Chile",
      "estAnnualEmissionReductions": 13103,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1838",
      "resourceName": "Renewable Energy Wind Power Project in Karnataka",
      "proponent": "Vish Wind Infrastructure LLP",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 12294,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1839",
      "resourceName": "CECIC HKC Danjinghe Wind Farm Project",
      "proponent": "CECIC HKE Wind Power CO.,LTD",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 471661,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "693",
      "resourceName": "Erkenek 12 MW Hydropower Plant, Turkey",
      "proponent": "Tektuð Elektrik Üretim A.Þ.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkmenistan",
      "estAnnualEmissionReductions": 32195,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1836",
      "resourceName": "Guanaquitas 9.74 MW Hydroelectric Project",
      "proponent": "Guanaquitas S.A.S .ES.P.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 21973,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-04"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1834",
      "resourceName": "60 MW Solar by Solarsys Non Conventional Energy Pvt. Ltd. - Ilkal.",
      "proponent": "WeAct Pty Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Withdrawn",
      "country": "India",
      "estAnnualEmissionReductions": 87651,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-03"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1835",
      "resourceName": "Caruquia 9.76 MW Hydroelectric Project",
      "proponent": "Caruquia S.A.S .ES.P.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 20303,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-12-03"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1832",
      "resourceName": "Haidong Afforestation Project",
      "proponent": "Qinghai Forestry Ecological Construction and Investment Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 598145,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-29"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1831",
      "resourceName": "Wind Energy Project at Devbhoomi Dwaraka,Gujarat by Powerica Limited",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 42210,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1197",
      "resourceName": "Chakala Wind Power Project in Maharashtra",
      "proponent": "M/s Bindu Vayu Urja Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 74307,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1207",
      "resourceName": "Sinner Wind Power Project in Maharashtra",
      "proponent": "M/s Bindu Vayu Urja Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 54247,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1827",
      "resourceName": "Mahuangliang Wind Project",
      "proponent": "Yulin Yihong New Energy Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "China",
      "estAnnualEmissionReductions": 165686,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1828",
      "resourceName": "Biomass based independent power project at Malwa Power Private Limited, Mukatsar, Punjab",
      "proponent": "Malwa Power Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 43854,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1829",
      "resourceName": "Biomass based power project in Punjab, India",
      "proponent": "Dee Development Engineers Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "India",
      "estAnnualEmissionReductions": 42657,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1830",
      "resourceName": "Wind Power Project at Theni by Powerica Limited",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 22798,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1825",
      "resourceName": "Afforestation Project in Xining City",
      "proponent": "Qinghai Forestry Ecological Construction and Investment Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 499982,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1826",
      "resourceName": "Qinghai Afforestation Project",
      "proponent": "Qinghai Forestry Ecological Construction and Investment Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 766948,
      "region": "Asia",
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-26"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1824",
      "resourceName": "Liucheng Biomass Power Generation Project",
      "proponent": "Liuzhou City Xin’neng Biomass Power Generation Co., Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "China",
      "estAnnualEmissionReductions": 123324,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002, ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1821",
      "resourceName": "Conservación de los Ecosistemas y el Almacén de Carbono Región de Transición Guayano Amazónica 'Flor de Inírida'",
      "proponent": "Ciprogress Greenlife",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use, Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registration requested",
      "country": "Colombia",
      "estAnnualEmissionReductions": 7627523,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0007",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1822",
      "resourceName": "10 MW wind power project by Powerica at BDS - Gujarat",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 24816,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1823",
      "resourceName": "21.8 MW Wind Power Project at Jangi Vandhiya, Gujarat by Powerica Limited",
      "proponent": "POWERICA LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 50207,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1819",
      "resourceName": "19.2 MWp Solar Power Project by HZL at Debari and Dariba, Rajasthan",
      "proponent": "Hindustan Zinc Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 23859,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1820",
      "resourceName": "Manantiales Behr Wind Farm",
      "proponent": "YPF Energia Electrica S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Argentina",
      "estAnnualEmissionReductions": 251000,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1817",
      "resourceName": "Reliance Composting Project in Cape Town",
      "proponent": "Reliance Group Trading (Pty) Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Waste handling and disposal",
      "resourceStatus": "Registered",
      "country": "South Africa",
      "estAnnualEmissionReductions": 49175,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-III.F.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "32",
      "resourceName": "Luara Ceramic Fuel Switching Project",
      "proponent": "Social Carbon Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 9450,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C., AMS-III.E.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-11-05"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1814",
      "resourceName": "Wind Power Project in Gujarat, India",
      "proponent": "Vish Wind Infrastructure LLP",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 57170,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1815",
      "resourceName": "Renewable Solar Power Project by Adani Green Energy Limited",
      "proponent": "Adani Green Energy Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1553021,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1816",
      "resourceName": "Wind power project in Tirunelveli Tamilnadu",
      "proponent": "Vaayu Renewable Energy (Tapti) Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 16347,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "345",
      "resourceName": "Wind power project by HZL in Karnataka.",
      "proponent": "Hindustan Zinc Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 65036,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "344",
      "resourceName": "Wind power project by HZL in Gujarat.",
      "proponent": "Hindustan Zinc Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 158127,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "120",
      "resourceName": "Aydin Salavatli Dora-1 Geothermal Power Plant",
      "proponent": "Menderes Geothermal Elektrik Uretim A.S",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Turkey",
      "estAnnualEmissionReductions": 30309,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-23"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "829",
      "resourceName": "Jatropha Curcas grouped project in Mali",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Mali",
      "estAnnualEmissionReductions": 3,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-AMS0004",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "922",
      "resourceName": "Plantation Project on wastelands by Sun Plant Agro Limited",
      "proponent": "Sun Plant Agro Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1708,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-AMS0005",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1327",
      "resourceName": "Reforestation of deforested land in Madagascar",
      "proponent": "EcoFormation",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Madagascar",
      "estAnnualEmissionReductions": 94452,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1811",
      "resourceName": "Jari/Pará REDD+ Project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 525314,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "VM0015",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1812",
      "resourceName": "VTRM Renewable Energy",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 652150,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1810",
      "resourceName": "Tri-Mid, LLC",
      "proponent": "Southern Power Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "United States",
      "estAnnualEmissionReductions": 375765,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-15"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1808",
      "resourceName": "Ruso Wind Partners, LLC",
      "proponent": "Southern Power Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "United States",
      "estAnnualEmissionReductions": 675077,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-12"
    }
  ]
}

module.exports = {
  vcs
}