const vcs = {
  "totalCount": 2026,
  "countExceeded": true,
  "@count": 2000,
  "value": [
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1150",
      "resourceName": "Algoma Highlands Conservancy Improved Forest Management Project",
      "proponent": "Algoma Highlands Conservancy",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Withdrawn",
      "country": "Canada",
      "estAnnualEmissionReductions": 1820,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "VM0010",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-12"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1807",
      "resourceName": "Biomass based thermal energy generation project by Dynamic Fine Paper Mill at Polai Kalan, Deegod, Kota",
      "proponent": "Dynamic Fine Paper Mill Pvt. Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 23470,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "746",
      "resourceName": "Pawan Urja Vistaran: Small entities combined wind power project in India - 2004",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 21539,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-10-09"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1806",
      "resourceName": "Riscales REDD+ Project",
      "proponent": "CONSEJO COMUNITARIO GENERAL LOS RISCALES",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Under validation",
      "country": "Colombia",
      "estAnnualEmissionReductions": 187240,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "VM0007",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-28"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1805",
      "resourceName": "Solar Energy Project(s) by SB Energy Private Limited",
      "proponent": "SB Energy Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 4354646,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "436",
      "resourceName": "Bundled Wind Power Project structured by KKSK",
      "proponent": "RADE WIND ENERGY PRIVATE LIMITED",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 28961,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "768",
      "resourceName": "Dalmia Chini Mills Jawaharpur Project",
      "proponent": "Dalmia Bharat Sugar and Industries Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 34581,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0006",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-24"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1804",
      "resourceName": "Combio Renewable Biomass Project - Três Marias",
      "proponent": "Combio Energia S.A.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 58519,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1803",
      "resourceName": "Distribution of ONIL Stoves – Mexico, CPA 002",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Mexico",
      "estAnnualEmissionReductions": 40089,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-II.G.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-19"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1802",
      "resourceName": "Philip Wind Partners, LLC",
      "proponent": "Southern Power Company",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under development",
      "country": "United States",
      "estAnnualEmissionReductions": 747057,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1191",
      "resourceName": "Jamanwada Wind Power Project in Gujarat",
      "proponent": "Bindu Vayu Urja Private Limited (BVUPL)",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 99897,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-11"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1190",
      "resourceName": "Wind power project in Gujarat",
      "proponent": "Mytrah Energy (INDIA) Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 48273,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1195",
      "resourceName": "Wind Power Project in Rajasthan",
      "proponent": "Mytrah Energy (INDIA) Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 70677,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1800",
      "resourceName": "12 MW Raura Hydro Project by DLI Power",
      "proponent": "DLI Power (India) Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "India",
      "estAnnualEmissionReductions": 56202,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-09-07"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "420",
      "resourceName": "Bundled 13.75 MW Wind Power Project in the state of Rajasthan and Maharashtra, India.",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 21879,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-30"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1799",
      "resourceName": "Forest management to mitigate climate change in Bélgica native community, Madre de Dios region – Peru",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registration requested",
      "country": "Peru",
      "estAnnualEmissionReductions": 126168,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "VM0015",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-29"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "663",
      "resourceName": "8.0 MW Wind Power Project activity by Sree Iswarya Textiles Private Limited, at Dist Erode, Tamil Nadu",
      "proponent": "Sree Iswarya Textiles Pvt Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 17219,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.D.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1798",
      "resourceName": "Hydroelectric projects at Oibita River",
      "proponent": "PCH San Bartolomé S.A.S .ES.P.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 100508,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-22"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1796",
      "resourceName": "Santa Rosa-Altamira hydroelectric projects",
      "proponent": "Desarrollo de Energías Renovables S.A.S .ES.P.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registration requested",
      "country": "Colombia",
      "estAnnualEmissionReductions": 99804,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1797",
      "resourceName": "El Molino-San Matias hydroelectric projects",
      "proponent": "PCHS Los Molinos S.A.S .ES.P.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 90393,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-20"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1794",
      "resourceName": "Interwaste Landfill gas Grouped Project",
      "proponent": "Interwaste (Pty) Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Waste handling and disposal",
      "resourceStatus": "Registered",
      "country": "South Africa",
      "estAnnualEmissionReductions": 41396,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0001",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-16"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1787",
      "resourceName": "Renewable Power Project by Animala Wind Power Private Limited",
      "proponent": "Animala Wind Power Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 163843,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1788",
      "resourceName": "Renewable Power Project by Saipuram Wind Energies Private Limited",
      "proponent": "Saipuram Wind Energies Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 266287,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1789",
      "resourceName": "Renewable Power Project by SEI Kathiravan Power Private Limited",
      "proponent": "SEI Kathiravan Power Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 77356,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1790",
      "resourceName": "Renewable Power Project by Axis Wind Farms (MPR Dam) Private Limited",
      "proponent": "Axis Wind Farms (MPR Dam) Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 195052,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1791",
      "resourceName": "Pavagada Solar Renewable Power Project by Greenko Group",
      "proponent": "SEI Suryashakti Power Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 139239,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1792",
      "resourceName": "Ghani Solar Renewable Power Project by Greenko Group",
      "proponent": "Zuvan Energy Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 996010,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1793",
      "resourceName": "Renewable Power Project by Devarahipparigi Wind Power Private Limited",
      "proponent": "Devarahipparigi Wind Power Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 195052,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "760",
      "resourceName": "Rice Husk Fired Boiler of 8 ton capacity for process steam generation, at Sara Textiles Limited, Baddi, Nalagarh, Himachal Pradesh",
      "proponent": "Sara Textiles Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 13645,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-14"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1784",
      "resourceName": "Solar Power Project by Mytrah Energy India Private Limited",
      "proponent": "Mytrah Energy (INDIA) Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources), Mining/mineral production",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 638520,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1786",
      "resourceName": "Solar Photovoltaic Project by Giriraj Renewables Private Limited",
      "proponent": "Giriraj Renewables Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1049469,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1782",
      "resourceName": "Solar PV Power Project by Prayatna Developers Pvt. Ltd. at Bhatinda, Punjab",
      "proponent": "Prayatna Developers Private Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 167973,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1783",
      "resourceName": "72 MWac Ramnad Renewable Energy Project",
      "proponent": "Ramnad Renewable Energy Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 115817,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-08-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1781",
      "resourceName": "MRMPL Wind Power Project",
      "proponent": "Modern Road Makers Pvt Ltd.",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 32788,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-31"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "250",
      "resourceName": "Bundled Wind Power Project in Tamilnadu, India, Co-ordinated by Tamilnadu Spinning Mills Association(TASMA-V1)",
      "proponent": "TAMILNADU SPINNING MILLS ASSOCIATION (TASMA)",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 82064,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-27"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "799",
      "resourceName": "Bukaleba Forest Project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Uganda",
      "estAnnualEmissionReductions": 11903,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AR-ACM0001",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-23"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1778",
      "resourceName": "Lahendong Unit 5 & Unit 6 Geothermal Project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Indonesia",
      "estAnnualEmissionReductions": 181030,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-17"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1774",
      "resourceName": "Grid-connected Solar PV project in Bokhol",
      "proponent": "Senergy 2 SAS",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Senegal",
      "estAnnualEmissionReductions": 22851,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1775",
      "resourceName": "Luangwa Community Forests Project",
      "proponent": "BioCarbon Partners",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Zambia",
      "estAnnualEmissionReductions": 2985650,
      "region": "Africa",
      "version": "VCS Version 3",
      "protocols": "VM0009",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1776",
      "resourceName": "Wind Power Project by Green Infra Wind Power Generation Limited",
      "proponent": "Green Infra Wind Power Generation Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 79147,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-10"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "982",
      "resourceName": "Combined cycle natural gas based grid connected power plant at Jegurupadu, India",
      "proponent": "GVK Industries Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 630005,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0029",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-07-02"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1772",
      "resourceName": "Solar and Wind Power Project by NTPC Limited",
      "proponent": "NTPC Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 940891,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-29"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1388",
      "resourceName": "Biomass based cogeneration project at Bihar, India",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Under validation",
      "country": "India",
      "estAnnualEmissionReductions": 75764,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.C.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "837",
      "resourceName": "Natural Gas Based Combined Cycle Power Generation, at Kothapeta, East Godavari, Andhra Pradesh, India",
      "proponent": "Konaseema Gas Power Ltd",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 1358857,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AM0029",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-25"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "34",
      "resourceName": "Cavalcante Ceramic fuel switching project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 17139,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.E.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-22"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "198",
      "resourceName": "J L Silva Ceramic Fuel Switching Project",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "Brazil",
      "estAnnualEmissionReductions": 20941,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "AMS-I.E.",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-22"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1771",
      "resourceName": "46 MW Mangoli Wind Power Project in Karnataka",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 120268,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-21"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1770",
      "resourceName": "Bundled Solar Power Project by Vector Green Energy Private Limited",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 163888,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-18"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1769",
      "resourceName": "Grouped Project for restoration of degraded lands in Jaguar Corridors, Colombia",
      "proponent": "Multiple Proponents",
      "operator": null,
      "designee": null,
      "protocolCategories": "Agriculture Forestry and Other Land Use",
      "resourceStatus": "Registered",
      "country": "Colombia",
      "estAnnualEmissionReductions": 6835,
      "region": "Latin America",
      "version": "VCS Version 3",
      "protocols": "VM0005, AR-ACM0003",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-06-06"
    },
    {
      "program": "Verified Carbon Standard",
      "resourceIdentifier": "1768",
      "resourceName": "216 MWac Kamuthi Solar Power Project",
      "proponent": "Kamuthi Solar Power Limited",
      "operator": null,
      "designee": null,
      "protocolCategories": "Energy industries (renewable/non-renewable sources)",
      "resourceStatus": "Registered",
      "country": "India",
      "estAnnualEmissionReductions": 346117,
      "region": null,
      "version": "VCS Version 3",
      "protocols": "ACM0002",
      "compatibleProgramScenarioTypeName": null,
      "createDate": "2018-05-31"
    }
  ]
}

module.exports = {
  vcs
}